development:
  domain: localhost:3000
  brand: ipcon
  codename: ipcon
  log: log/ipcon.log

test:
  domain: test.host
  brand: ipcon test
  codename: ipcon2
  log: log/ipcon.log


production:
  domain: example.com
  brand: ipcon
  codename: ipcon
  log: log/ipcon.log
